shoreline/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Blacklight::Engine => "/"
  root to: "catalog#index"
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog,
    only: [:index],
    as: "catalog",
    path: "/catalog",
    controller: "catalog" do
    concerns :searchable
  end
  devise_for :users
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents,
    only: [:show],
    path: "/catalog",
    controller: "catalog" do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete "clear"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Geoblacklight::Engine => "geoblacklight"
  concern :gbl_exportable, Geoblacklight::Routes::Exportable.new
  resources :solr_documents,
    only: [:show],
    path: "/catalog",
    controller: "catalog" do
    concerns :gbl_exportable
  end
  concern :gbl_wms, Geoblacklight::Routes::Wms.new
  namespace :wms do
    concerns :gbl_wms
  end
  concern :gbl_downloadable, Geoblacklight::Routes::Downloadable.new
  namespace :download do
    concerns :gbl_downloadable
  end
  resources :download, only: [:show]

  # Contact form routes
  post "contact" => "contact_form#create", :as => :contact_form_index
  get "contact" => "contact_form#new"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if ENV.fetch("DELIVERY_METHOD", "").eql? "letter_opener_web"
end

shoreline/app/views/shared/_header_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark topbar" role="navigation">
  <div class="<%= container_classes %>">
    <%= link_to application_name, root_path, class: 'mb-0 navbar-brand' %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#user-util-collapse" aria-controls="user-util-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-md-end" id="user-util-collapse">
      <%= render 'shared/user_util_links' %>
    </div>
  </div>
</nav>

shoreline/app/views/shared/_header_navbar_ucla.html.erb
<header id="navbar" class="navbar navbar-expand-md topbar" role="navigation">
  <div id="eyebrow" class="<%= container_classes %>">
    <%= link_to "UCLA Library", root_path, class: "edu-link" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#user-util-collapse" aria-controls="user-util-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="justify-content-md-end">
      <%= render 'shared/user_util_links' %>
    </div>
  </div>
</header>

<div class="navbar-search navbar navbar-light bg-light" role="navigation">
  <div class="<%= container_classes %>">
    <%= render_search_bar  %>
  </div>
</div>

shoreline/app/views/shared/_header_navbar_ucsb.html.erb
<header id="navbar" class="navbar navbar-expand-md topbar" role="navigation">
  <div id="eyebrow" class="<%= container_classes %>">
    <%= link_to "University of California, Santa Barbara", root_path, class: "edu-link" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#user-util-collapse" aria-controls="user-util-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="justify-content-md-end">
      <%= render 'shared/user_util_links' %>
    </div>
  </div>
</header>

<div class="navbar-search navbar navbar-light bg-light" role="navigation">
  <div class="<%= container_classes %>">
    <%= render_search_bar  %>
  </div>
</div>

shoreline/app/views/shared/_user_util_links.html.erb
<ul class="navbar-nav">
  <%= render_nav_actions do |config, action|%>
    <li class="nav-item"><%= action %></li>
  <% end %>
  <li class="nav-item">
    <%= link_to t('blacklight.header_links.contact'), contact_form_index_path, class: 'nav-link' %>
  </li>

  <% if has_user_authentication_provider? %>
    <% if current_user %>
    <li class="nav-item">
      <%= link_to t('blacklight.header_links.logout'), destroy_user_session_path, class: 'nav-link' %>
    </li>
    <% unless current_user.to_s.blank? -%>
    <li class="nav-item">
      <%= link_to current_user, edit_user_registration_path, class: 'nav-link' %>
    </li>
    <% end %>
    <% else %>
    <li class="nav-item">
      <%= link_to t('blacklight.header_links.login'), new_user_session_path, class: 'nav-link' %>
    </li>
    <% end %>
  <% end %>
</ul>